# -*- coding: utf-8 -*-
"""LSTM2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RItGt81WeciTwiAEc452zSb4btrN8c0
"""

!pip install tensorflow
!pip install keras

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import tensorflow as tf

# متن ورودی
text = "Spring is a beautiful season. It is the time of year when the cold, harsh winter begins to fade away and the world comes alive once again. The trees start to bud, the flowers begin to bloom, and the air is filled with the sweet scent of new growth.As I sit here, looking out at the world around me, I can't help but feel a sense of joy and renewal. The grass is a vibrant green, and the sun is shining brightly in the clear blue sky. Children are playing outside, their laughter filling the air, and birds are singing their sweet songs.Spring is a time of new beginnings. It is a time to start fresh, to let go of the past and look forward to the future. It is a time to set new goals and to work towards achieving them. It is a time to plant seeds and watch them grow into beautiful flowers and delicious vegetables.As I walk through the park, I am surrounded by the beauty of spring. The cherry blossoms are in full bloom, their delicate pink petals fluttering in the breeze. The daffodils and tulips are a burst of color, their bright yellow and orange petals a stark contrast to the green grass.Spring is a time of love and romance. It is a time when couples walk hand in hand, their hearts filled with joy and happiness. It is a time when love is in the air, and anything seems possible.As I sit on a bench, watching the world go by, I can't help but feel grateful for this beautiful season. Spring is a time of hope and renewal, a time to start anew and to appreciate the beauty of the world around us.Spring is a beautiful season. It is a time of growth and renewal, a time to appreciate the beauty of the world around us. It is a time to set new goals and to work towards achieving them. It is a time to plant seeds and watch them grow into beautiful flowers and delicious vegetables.As I walk home, I am filled with a sense of peace and contentment. Spring is a beautiful season, and I am grateful for every moment of it"

# توکن‌ایزر
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1

# تبدیل متن به دنباله‌های ورودی و خروجی
input_sequences = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

# پدینگ دنباله‌ها
max_sequence_length = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre'))

# تعریف مدل LSTM
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_length-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# آموزش مدل
X = input_sequences[:,:-1]
y = input_sequences[:,-1]
y = tf.keras.utils.to_categorical(y, num_classes=total_words)
model.fit(X, y, epochs=20, verbose=1)

# تابع پیش‌بینی کلمه بعدی
def predict_next_word(seed_text):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list),axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    return output_word

# پیش‌بینی کلمه بعدی برای یک seed text خاص
next_word = predict_next_word("spring is a beautiful")
print(next_word)