# -*- coding: utf-8 -*-
"""third code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSWt4pCmivqIJEGmgDZsLu2pXfFGpfaU
"""

import nltk
from nltk.util import bigrams
from nltk.probability import FreqDist
from nltk.tokenize import word_tokenize

nltk.download('punkt')

def calculate_bigram_probability(text, sentence):
    words = word_tokenize(text.lower())
    bigram = list(bigrams(words))
    fdist = FreqDist(bigram)

    sentence_bigram = list(bigrams(word_tokenize(sentence.lower())))

    total_bigrams = len(bigram)
    sentence_probability = 1.0

    for bg in sentence_bigram:
        sentence_probability *= fdist[bg] / total_bigrams

    return sentence_probability

# Example Usage
english_text = "Spring is a beautiful season. It is the time of year when the cold, harsh winter begins to fade away and the world comes alive once again. The trees start to bud, the flowers begin to bloom, and the air is filled with the sweet scent of new growth.As I sit here, looking out at the world around me, I can't help but feel a sense of joy and renewal. The grass is a vibrant green, and the sun is shining brightly in the clear blue sky. Children are playing outside, their laughter filling the air, and birds are singing their sweet songs.Spring is a time of new beginnings. It is a time to start fresh, to let go of the past and look forward to the future. It is a time to set new goals and to work towards achieving them. It is a time to plant seeds and watch them grow into beautiful flowers and delicious vegetables.As I walk through the park, I am surrounded by the beauty of spring. The cherry blossoms are in full bloom, their delicate pink petals fluttering in the breeze. The daffodils and tulips are a burst of color, their bright yellow and orange petals a stark contrast to the green grass.Spring is a time of love and romance. It is a time when couples walk hand in hand, their hearts filled with joy and happiness. It is a time when love is in the air, and anything seems possible.As I sit on a bench, watching the world go by, I can't help but feel grateful for this beautiful season. Spring is a time of hope and renewal, a time to start anew and to appreciate the beauty of the world around us.Spring is a beautiful season. It is a time of growth and renewal, a time to appreciate the beauty of the world around us. It is a time to set new goals and to work towards achieving them. It is a time to plant seeds and watch them grow into beautiful flowers and delicious vegetables.As I walk home, I am filled with a sense of peace and contentment. Spring is a beautiful season, and I am grateful for every moment of it."
given_sentence = "Spring is a beautiful season"

sentence_probability = calculate_bigram_probability(english_text, given_sentence)
print(f"The probability of the given sentence occurring in the text is: {sentence_probability}")